In [1]:
ls

Cleaned Data Set.csv                  Natality EDA-Copy1.ipynb
Cleaned Data Set.xls                  Parser Test.py
Data Dictionary.ipynb                 Parsers/
Mo Parser-Archive.ipynb               Raw Data Sets/
Natality - Data Cleaning-Copy1.ipynb  Tableau Ready CSV.ipynb
Natality - Data Cleaning.ipynb        User Guides/
Natality Dataset.csv                  import_natality.sql
Natality EDA - Scratch.ipynb


In [2]:
import pandas as pd
import numpy as np
import re

In [10]:
%time df0 = pd.read_csv('Natality Dataset.csv')
# %time df0 = pd.read_csv('Raw Data Sets/Total Sampled Data.csv')

CPU times: user 13.4 s, sys: 2.82 s, total: 16.2 s
Wall time: 15.6 s


In [40]:
list(df0.columns)

['birth_year',
 'birth_month',
 'birth_time',
 'birth_day_of_wk',
 'birth_place',
 'mothers_age',
 'mothers_nativity',
 'mothers_residence_status',
 'mothers_race',
 'mothers_hispanic_origin',
 'mothers_hispanic_origin2',
 'paternity_acknow',
 'mothers_marital_status',
 'mothers_education',
 'fathers_age',
 'fathers_race',
 'fathers_hispanic_origin',
 'fathers_hispanic_origin2',
 'fathers_education',
 'prior_living_births',
 'prior_dead_births',
 'prior_terminations',
 'mo_prenatal_care_began',
 'n_prenatal_visits',
 'wic',
 'cigs_tri1',
 'cigs_tri2',
 'cigs_tri3',
 'pre_preg_diab',
 'gest_diab',
 'pre_preg_hypten',
 'gest_hypten',
 'hypten_ecl',
 'prev_preterm_birth',
 'infertility_treatment',
 'fertil_enhance',
 'asst_repro_tech',
 'n_prev_cesar',
 'gonorrhea',
 'syphilis',
 'chlamydia',
 'hepB',
 'hepC',
 'success_ext_cep',
 'fail_ext_cep',
 'induced_labor',
 'aug_labor',
 'steriods',
 'antibiotics',
 'chorioamnionitis',
 'anesthesia',
 'fetal_present_at_birth',
 'final_delivery_met

##### Drop Unnamed and Imputed columns
Drop the following columns
- Imputed
- Unnamed

In [12]:
df0 = df0.drop(['Unnamed: 0','Unnamed: 0.1', 'mothers_age_imputed','mothers_race_imputed', 'mothers_maristat_imputed', 'pluarlity_imputed',
               'sex_of_infant_imputed', 'combined_gestation_imputed','obst_est_of_gestation_used'], axis = 1)


In [ ]:
# Check if there are any null values for birth_year
df0[df0.birth_year.isnull()]

In [23]:
# Drop null values for birth_year
df0 = df0[df0.birth_year.notnull()]

In [108]:
# Review unique values in each column
for col in df0:
    print(df0[col].unique())
    print(col)

[2013 2014 2015 2016 2017]
birth_year
[ 5  4  3  8 10  6  1 11 12  2  7  9]
birth_month
[1209 2105  814 ...  603  608  320]
birth_time
[5 6 4 2 3 7 1]
birth_day_of_wk
[1 9 2 3 5 7 4 6]
birth_place
[19 25 31 27 32 35 22 38 28 39 26 33 30 34 23 29 20 36 21 24 37 45 17 18
 41 40 16 13 42 43 15 46 44 48 50 47 14 49 12]
mothers_age
[3 1 2]
mothers_nativity
[0 1 2 3 4]
mothers_residence_status
[99  1  2 78 18  3  7 28  4  6 48 68  5 58 10 16 13  8 25 15 11 14 19  9
 17 22 23 24 21 26 30 29 12 31 20 27]
mothers_race
[0 5 1 3 4 2 9]
mothers_hispanic_origin
[7 6 5 1 3 4 8 2 9]
mothers_hispanic_origin2
['N' 'X' 'Y' 'U']
paternity_acknow
[2 1 9]
mothers_marital_status
[2 4 3 7 9 6 5 8 1]
mothers_education
[99  1 40 41 32 29 34 28 19 43 24 37 25 20 23 35 36 33 39 27 42 30 38 45
 31 44 61 22 26 21 17 62 47 52 46 48 57 49 53 18 50 54 56 63 51 71 60 59
 16 55 15 65 14 58 67 66 70 69 68 64 75 74 73 82 72 78 13 76 79 81]
fathers_age
[99  1  2 22  5 10  4 14  9  3 24 21  6  8  7 13 23 11 12 19 25 16 15 

[0 1]
pre_preg_diab_reporting
[0 1]
gest_diab_reporting
[0 1]
pre_preg_hypten_reporting
[0 1]
gest_hypten_reporting
[0 1]
hypten_ecl_reporting
[0 1]
prev_preterm_birth_reporting
[(40.0, 100.0], (19.0, 25.0], (30.0, 35.0], (25.0, 30.0], (0.0, 19.0], (35.0, 40.0]]
Categories (6, interval[float64]): [(0.0, 19.0] < (19.0, 25.0] < (25.0, 30.0] < (30.0, 35.0] < (35.0, 40.0] < (40.0, 100.0]]
mother_bmi_recode
[12-19, 20-29, 30-39, 40-50]
Categories (4, object): [12-19 < 20-29 < 30-39 < 40-50]
mothers_age_groups
[(1999, 2499], (2999, 3499], (3999, 4499], (3499, 3999], (2499, 2999], ..., (4499.0, 4999.0], NaN, (999.0, 1499.0], (499.0, 999.0], (0.0, 499.0]]
Length: 12
Categories (11, interval[int64]): [(0, 499] < (499, 999] < (999, 1499] < (1499, 1999] ... (3499, 3999] < (3999, 4499] < (4499, 4999] < (4999, 8200]]
birth_weight_recode
['2013-05-01T00:00:00.000000000' '2013-04-01T00:00:00.000000000'
 '2013-03-01T00:00:00.000000000' '2013-08-01T00:00:00.000000000'
 '2013-10-01T00:00:00.000000000' '

In [71]:
# Function to replace missing values in reporting columns with '0' for non reported

def reporting_replace_missingness(df):
    return df.replace(np.nan, '0')

r = re.compile(".*reporting")
reporting_columns = list(filter(r.match, df0.columns))
df0[reporting_columns] = df0[reporting_columns].apply(reporting_replace_missingness)

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [69]:
# Replace missing value with "99" for unknown months of prenatal care start

df0['mo_prenatal_care_began'] = df0['mo_prenatal_care_began'].replace(' ', '99')
df0['mo_prenatal_care_began'] = df0['mo_prenatal_care_began'].replace('  ', '99')
df0['fathers_race'] = df0['fathers_race'].replace(' ', '99') #check index 908112
df0['fathers_race'] = df0['fathers_race'].replace('  ', '99')
df0['fathers_age'] = df0['fathers_age'].replace('  ', '99')
df0['fathers_age'] = df0['fathers_age'].replace(' ', '99')
df0['attendant_at_birth'] = df0['attendant_at_birth'].replace(' ', 9).replace('U', 9).replace('Y', 9).replace('N', 9)
df0['obst_est_edit_wk'] = df0['obst_est_edit_wk'].replace('1', '99').replace(' ', 99)

df0['mothers_race'] = df0['mothers_race'].replace('  ', '99')
df0['cigs_before'] = df0['cigs_before'].replace(np.nan, '99')
df0['weight_gain'] = df0['weight_gain'].replace(np.nan, '99')
df0['mo_since_last_other_birth'] = df0['mo_since_last_other_birth'].replace(np.nan, '999')
df0['birth_time'] = df0['birth_time'].replace('    ', '9999')

# Replace missing value with "9" for unknown parent education and marital status

df0['mothers_nativity'] = df0['mothers_nativity'].replace('  ', '3')
df0['mothers_residence_status'] = df0['mothers_residence_status'].replace('  ', '0')
df0['mothers_marital_status'] = df0['mothers_marital_status'].replace(' ', '9')
df0['mothers_education'] = df0['mothers_education'].replace(' ', '9')
df0['fathers_education'] = df0['fathers_education'].replace(' ', '9')
df0['fathers_hispanic_origin2'] = df0['fathers_hispanic_origin2'].replace(np.nan, '9')
df0['fathers_hispanic_origin2'] = df0['fathers_hispanic_origin2'].replace(' ', '9')
df0['mothers_bmi_recode'] = df0['mothers_bmi_recode'].replace(np.nan, '9')

# Replace missing value or empty string ' ' with "U" for unknown

df0['wic'] = df0['wic'].replace(np.nan, 'U')
df0['wic'] = df0['wic'].replace(' ', 'U')
df0['admit_NICU'] = df0['admit_NICU'].replace(' ', 'U')
df0['pre_preg_diab'] = df0['pre_preg_diab'].replace(' ', 'U')
df0['gest_diab'] = df0['gest_diab'].replace(' ', 'U')
df0['pre_preg_hypten'] = df0['pre_preg_hypten'].replace(' ', 'U')
df0['gest_hypten'] = df0['gest_hypten'].replace(' ', 'U')
df0['hypten_ecl'] = df0['hypten_ecl'].replace(' ', 'U')
df0['prev_preterm_birth'] = df0['prev_preterm_birth'].replace(' ', 'U')
df0['paternity_acknow'] = df0['paternity_acknow'].replace(' ', 'U') #check index 805890

# replace missing values of reporting columns with '0' for not reported
df0['mothers_height_reporting'] = df0['mothers_height_reporting'].replace(np.nan, '0')
df0['pre_preg_lbs_reporting'] = df0['pre_preg_lbs_reporting'].replace(np.nan, '0')
df0['weight_gain_reporting'] = df0['weight_gain_reporting'].replace(np.nan, '0')
df0['pre_preg_diab_reporting'] = df0['pre_preg_diab_reporting'].replace(np.nan, '0')
df0['gest_diab_reporting'] = df0['gest_diab_reporting'].replace(np.nan, '0')
df0['pre_preg_hypten_reporting'] = df0['pre_preg_hypten_reporting'].replace(np.nan, '0')
df0['gest_hypten_reporting'] = df0['gest_hypten_reporting'].replace(np.nan, '0')
df0['hypten_ecl_reporting'] = df0['hypten_ecl_reporting'].replace(np.nan, '0')
df0['prev_preterm_birth_reporting'] = df0['prev_preterm_birth_reporting'].replace(np.nan, '0')
df0['delivery_lbs_reporting'] = df0['delivery_lbs_reporting'].replace(np.nan, '0')

df0['birth_place'] = df0['birth_place'].replace(' ', '9')
df0['mothers_race'] = df0['mothers_race'].replace(' ', '99')
df0['mothers_hispanic_origin'] = df0['mothers_hispanic_origin'].replace(' ', '9')
df0['mothers_hispanic_origin2'] = df0['mothers_hispanic_origin2'].replace(' ', '8')
df0['fathers_hispanic_origin'] = df0['fathers_hispanic_origin'].replace(' ', '9')
df0['n_prenatal_visits'] = df0['n_prenatal_visits'].replace('  ', '99')
df0['cigs_tri1'] = df0['cigs_tri1'].replace('  ', '99')
df0['cigs_tri2'] = df0['cigs_tri2'].replace('  ', '99')
df0['cigs_tri3'] = df0['cigs_tri3'].replace('  ', '99')
df0['n_prev_cesar'] = df0['n_prev_cesar'].replace('  ', '99')
df0['fetal_present_at_birth'] = df0['fetal_present_at_birth'].replace(' ', '9')
df0['final_delivery_method'] = df0['final_delivery_method'].replace(' ', '9')
df0['delivery_payment_source'] = df0['delivery_payment_source'].replace(' ', '9')
df0['APGAR_score_10min'] = df0['APGAR_score_10min'].replace('  ', '99')
df0['APGAR_score_10min'] = df0['APGAR_score_10min'].replace(' ', '99')
df0['mo_since_last_live_birth'] = df0['mo_since_last_live_birth'].replace('   ', '999')
df0['mo_since_last_live_birth'] = df0['mo_since_last_live_birth'].replace(np.nan, '999')
df0['mo_since_last_other_birth'] = df0['mo_since_last_other_birth'].replace('   ', '999')
df0['mothers_height'] = df0['mothers_height'].replace('  ', '99')
df0['mothers_height'] = df0['mothers_height'].replace(np.nan, '99')
df0['pre_preg_lbs'] = df0['pre_preg_lbs'].replace('   ', '999')
df0['pre_preg_lbs'] = df0['pre_preg_lbs'].replace(np.nan, '999')
df0['delivery_lbs'] = df0['delivery_lbs'].replace('   ', '999')
df0['delivery_lbs'] = df0['delivery_lbs'].replace(np.nan, '999')
df0['no_risk_reported'] = df0['no_risk_reported'].replace(' ', '9')
df0['no_risk_reported'] = df0['no_risk_reported'].replace(np.nan, '9')
df0['no_infection_reported'] = df0['no_infection_reported'].replace(' ', '9')
df0['no_infection_reported'] = df0['no_infection_reported'].replace(np.nan, '9')
df0['no_cong_anamolies_checked'] = df0['no_cong_anamolies_checked'].replace(' ', '9')
df0['no_cong_anamolies_checked'] = df0['no_cong_anamolies_checked'].replace(np.nan, '9')

df0['mothers_bmi'] = df0['mothers_bmi'].replace('    ', '99.9')
df0['mothers_bmi'] = df0['mothers_bmi'].replace(np.nan, '99.9')

df0['infertility_treatment'] = df0['infertility_treatment'].replace(' ', 'U')
df0['fertil_enhance'] = df0['fertil_enhance'].replace(' ', 'U')
df0['asst_repro_tech'] = df0['asst_repro_tech'].replace(' ', 'U')
df0['gonorrhea'] = df0['gonorrhea'].replace(' ', 'U')
df0['syphilis'] = df0['syphilis'].replace(' ', 'U')
df0['chlamydia'] = df0['chlamydia'].replace(' ', 'U')
df0['hepB'] = df0['hepB'].replace(' ', 'U')
df0['hepC'] = df0['hepC'].replace(' ', 'U')
df0['success_ext_cep'] = df0['success_ext_cep'].replace(' ', 'U')
df0['fail_ext_cep'] = df0['fail_ext_cep'].replace(' ', 'U')
df0['induced_labor'] = df0['induced_labor'].replace(' ', 'U')
df0['aug_labor'] = df0['aug_labor'].replace(' ', 'U')
df0['steriods'] = df0['steriods'].replace(' ', 'U')
df0['antibiotics'] = df0['antibiotics'].replace(' ', 'U')
df0['chorioamnionitis'] = df0['chorioamnionitis'].replace(' ', 'U')
df0['anesthesia'] = df0['anesthesia'].replace(' ', 'U')

df0['trial_of_labor_attempt'] = df0['trial_of_labor_attempt'].replace(' ', 'U')
df0['maternal_transfusion'] = df0['maternal_transfusion'].replace(' ', 'U')
df0['perineal_laceration'] = df0['perineal_laceration'].replace(' ', 'U')
df0['rupt_uterus'] = df0['rupt_uterus'].replace(' ', 'U')
df0['unplanned_hyster'] = df0['unplanned_hyster'].replace(' ', 'U')
df0['admit_to_IC'] = df0['admit_to_IC'].replace(' ', 'U')


df0['mother_transferred'] = df0['mother_transferred'].replace(' ', 'U')
df0['assist_vent_immed'] = df0['assist_vent_immed'].replace(' ', 'U')
df0['assist_vent_after6'] = df0['assist_vent_after6'].replace(' ', 'U')
df0['admit_NICU'] = df0['admit_NICU'].replace(' ', 'U')
df0['surfactant'] = df0['surfactant'].replace(' ', 'U')
df0['antibiotics_for_newborn'] = df0['antibiotics_for_newborn'].replace(' ', 'U')
df0['seizures'] = df0['seizures'].replace(' ', 'U')
df0['anencephaly'] = df0['anencephaly'].replace(' ', 'U')
df0['meningo_spina_bif'] = df0['meningo_spina_bif'].replace(' ', 'U')
df0['cyn_cong_heart_disease'] = df0['cyn_cong_heart_disease'].replace(' ', 'U')
df0['cong_diaph_hernia'] = df0['cong_diaph_hernia'].replace(' ', 'U')
df0['omphalocele'] = df0['omphalocele'].replace(' ', 'U')
df0['gastroschisis'] = df0['gastroschisis'].replace(' ', 'U')
df0['limb_reduc_defect'] = df0['limb_reduc_defect'].replace(' ', 'U')
df0['cleft_lip_or_palate'] = df0['cleft_lip_or_palate'].replace(' ', 'U')
df0['cleft_palate_only'] = df0['cleft_palate_only'].replace(' ', 'U')
df0['down_syndr'] = df0['down_syndr'].replace(' ', 'U')
df0['suspect_chromo_disorder'] = df0['suspect_chromo_disorder'].replace(' ', 'U')
df0['hypospadias'] = df0['hypospadias'].replace(' ', 'U')
df0['infant_transferred'] = df0['infant_transferred'].replace(' ', 'U')
df0['infant_living_at_report'] = df0['infant_living_at_report'].replace(' ', 'U')
df0['infant_breastfed_at_discharge'] = df0['infant_breastfed_at_discharge'].replace(' ', 'U')


/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try usin

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:34: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:35: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:36: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:63: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:64: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:65: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:90: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:91: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:92: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:117: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:118: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:119: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pand

In [77]:
pd.set_option('display.max_columns' ,None)

df0[int_col].head()

birth_year  birth_month  birth_time  birth_day_of_wk birth_place  \
0        2013            5        1209                5           1   
1        2013            4        2105                6           1   
2        2013            5         814                5           1   
3        2013            4        2037                4           1   
4        2013            3        1623                5           1   

   mothers_age mothers_nativity mothers_residence_status mothers_race  \
0         19.0                3                        0           99   
1         25.0                3                        0           99   
2         31.0                3                        0           99   
3         25.0                3                        0           99   
4         27.0                3                        0           99   

  mothers_hispanic_origin mothers_hispanic_origin2 mothers_marital_status  \
0                       0                        7                      2   
1                       0                        6                      1   
2                       0                        7                      2   
3                       0                        6                      1   
4                       0                        6                      1   

  mothers_education fathers_age fathers_race fathers_hispanic_origin  \
0                 2          99           99                       9   
1                 4          99            1                       0   
2                 3          99            2                       0   
3                 4          99            1                       0   
4                 7          99            1                       0   

  fathers_hispanic_origin2 fathers_education  prior_living_births  \
0                        9                 9                  1.0   
1                        6                 6                  1.0   
2                        7                 3                  6.0   
3                        6                 3                  1.0   
4                        6                 6                  2.0   

   prior_dead_births  prior_terminations mo_prenatal_care_began  \
0                1.0                 0.0                      4   
1                1.0                 0.0                      3   
2                8.0                 3.0                      6   
3                1.0                 0.0                      3   
4                2.0                 0.0                      2   

  n_prenatal_visits cigs_tri1 cigs_tri2 cigs_tri3 n_prev_cesar  \
0                11         0         0         0            0   
1                12         0         0         0            0   
2                 6         0         0         0            0   
3                14         0         0         0            0   
4                20         0         0         0            1   

  fetal_present_at_birth final_delivery_method attendant_at_birth  \
0                      1                     1                  9   
1                      1                     1                  9   
2                      1                     4                  9   
3                      1                     1                  9   
4                      1                     4                  9   

  delivery_payment_source  APGAR_score_5min APGAR_score_10min  plurality  \
0                       1               9.0                 8        1.0   
1                       2               8.0                 8        1.0   
2                       2               9.0                 8        1.0   
3                       2               9.0                 8        1.0   
4                       2               9.0                 8        1.0   

   last_norm_menses_mo  last_norm_menses_yr  combined_gestation_wk  \
0                  7.0               2012.0                   42.0   
1             

In [82]:
# cast columns to int
int_col = ['birth_year', 'birth_month', 'birth_time','birth_day_of_wk', 'birth_place', 'mothers_age', 'mothers_nativity',
'mothers_residence_status', 'mothers_race', 'mothers_hispanic_origin', 'mothers_hispanic_origin2',
'mothers_marital_status', 'mothers_education', 'fathers_age', 'fathers_race', 'fathers_hispanic_origin',
'fathers_hispanic_origin2', 'fathers_education', 'prior_living_births', 'prior_dead_births', 'prior_terminations',
'mo_prenatal_care_began', 'n_prenatal_visits',  'cigs_tri1', 'cigs_tri2', 'cigs_tri3', 'n_prev_cesar',
'fetal_present_at_birth', 'final_delivery_method', 'attendant_at_birth', 'delivery_payment_source',
'APGAR_score_5min', 'APGAR_score_10min', 'plurality', 'last_norm_menses_mo', 'last_norm_menses_yr',
'combined_gestation_wk', 'obst_est_edit_wk', 'birth_weight_gm', 
'mo_since_last_live_birth', 'mo_since_last_other_birth', 'mothers_height',  'pre_preg_lbs', 
'delivery_lbs', 'no_risk_reported', 'no_infection_reported',
'no_cong_anamolies_checked', 'cigs_before', 'mothers_height_reporting', 'mothers_bmi_recode','pre_preg_lbs_reporting',
'delivery_lbs_reporting', 'weight_gain', 'weight_gain_reporting', 'pre_preg_diab_reporting', 
'pre_preg_hypten_reporting', 'hypten_ecl_reporting','gest_diab_reporting', 'gest_hypten_reporting', 'prev_preterm_birth_reporting']




# cast columns to float

float_col = ['mothers_bmi', 'birth_time']

# cast columns to string
str_col = ['paternity_acknow', 'fathers_race', 'wic', 'pre_preg_diab', 'gest_diab', 'pre_preg_hypten', 'gest_hypten', 
'hypten_ecl', 'prev_preterm_birth', 'infertility_treatment', 'fertil_enhance', 'asst_repro_tech','gonorrhea', 
'syphilis', 'chlamydia', 'hepB', 'hepC', 'success_ext_cep', 'fail_ext_cep', 'induced_labor', 'aug_labor', 
'steriods', 'antibiotics', 'chorioamnionitis', 'anesthesia', 'trial_of_labor_attempt', 'maternal_transfusion', 
'perineal_laceration', 'rupt_uterus', 'unplanned_hyster', 'admit_to_IC', 'mother_transferred', 'sex_of_infant', 
'assist_vent_immed', 'assist_vent_after6', 'admit_NICU', 'surfactant','antibiotics_for_newborn', 'seizures', 
'anencephaly', 'meningo_spina_bif', 'cyn_cong_heart_disease', 'cong_diaph_hernia', 'omphalocele', 'gastroschisis', 
'limb_reduc_defect', 'cleft_lip_or_palate', 'cleft_palate_only', 'down_syndr', 'suspect_chromo_disorder', 
'hypospadias', 'infant_transferred', 'infant_living_at_report', 'infant_breastfed_at_discharge']


In [ ]:
df0.head()

In [73]:
for col in float_col:
    df0[col] = df0[col].apply(lambda x:float(x))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [83]:
for col in int_col:
    df0[col] = df0[col].apply(lambda x:float(x))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [84]:
for col in int_col:
    df0[col] = df0[col].apply(lambda x: int(x))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [75]:
for col in str_col:
    df0[col] = df0[col].apply(lambda x:str(x))

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


###### Feature Engineering

---------

    - New Column for Birth Year and Month

In [89]:
df0['birth_year_month'] = df0['birth_year'].astype(int).astype(str) + df0['birth_month'].astype(int).astype(str).str.zfill(2)
df0['birth_year_month'] = pd.to_datetime(df0['birth_year_month'], format = '%Y%m')

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


    - Creating/Binning groups for Mother's BMI

In [85]:
df0['mother_bmi_recode'] = pd.cut(df0['mothers_bmi'],[0.0,19.0,25.0,30.0,35.0,40.0,100.0])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


    - Creating/Binning groups for Mother's Age

In [86]:
df0['mothers_age_groups']= pd.cut(df0['mothers_age'], [0,14,19,24,29,34,39,44,49,100],
                                     labels = ['<15', '15-19', '20-24','25-29','30-34','35-39','40-44','45-49','50+'])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [87]:
df0['mothers_age_groups'] = pd.cut(df0['mothers_age'], 4, labels = ['12-19', '20-29', '30-39','40-50'])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


    - Creating/Binning groups for Newborn's Birth Weight

In [88]:
df0['birth_weight_recode'] = pd.cut(df0['birth_weight_gm'],[0,499,999,1499,1999,2499,2999,3499,3999,4499,4999,8200])

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


----

##### Output CSV file

In [113]:
df0.to_csv('Cleaned Data Set.csv',  index=False)

-------